### ISSUE TITLE
Fix "assignment to entry in nil map" Error in GetFriendshipStatusCall.Do Method

### ISSUE THREAD

**Issue by bluewolfali** [kkdai/line-social-sdk-go#10]
In the `GetFriendshipStatusCall.Do` method, there is a bug that causes a runtime panic with the error message "assignment to entry in nil map". This error occurs when trying to set a value in the `urlQuery` map, which has been declared but not initialized.

Here is the problematic code:

```go
func (call *GetFriendshipStatusCall) Do() (*GetFriendshipStatusResponse, error) {
	var urlQuery url.Values
	urlQuery.Set("access_token", call.accessToken)
	...
}
```

**Comment by kkdai** [comment]
It is fixed by #9
