### ISSUE TITLE
Version Tagging Issue: `v7.x.x` Should Be `v0.7.x` – `go get` Failing

### ISSUE THREAD

**Issue by bluewolfali** [kkdai/line-social-sdk-go#12]
I noticed that the recent version tags are labeled as `v7.x.x`, but based on the previous versions (`v0.6.1`, `v0.6.0`, etc.), I think these were intended to be `v0.7.x`.

When I try to run:

```bash
go get github.com/kkdai/line-login-sdk-go@v7.10.0
```

I receive the following error:

```
go: github.com/kkdai/line-login-sdk-go@v7.10.0: go.mod has non-... module path "github.com/kkdai/line-login-sdk-go" at revision v7.10.0
```

It seems that the `v7.x.x` tags are causing issues with `go get` due to Go modules' versioning rules.

Could you please check and correct the version tags? Changing them to `v0.7.x` might resolve the problem.

**Comment by bluewolfali** [comment]
It's a long vacation ww

**Comment by kkdai** [comment]
Sorry, let me fix it.

**Comment by kkdai** [comment]
Please check it again, thank @bluewolfali

**Comment by bluewolfali** [comment]
I’ve checked it and can now successfully download the latest version. Thank you!

**Comment by bluewolfali** [comment]
I’ve checked it and can now successfully download the latest version. Thank you!
