### ISSUE TITLE
path.Join wrongly combined URLs

### ISSUE THREAD

**Issue by minghsu0107** [kkdai/line-social-sdk-go#5]
In social.go, line 68 and line 124:
```go
// line 68
req, err := http.NewRequest("GET", path.Join(APIEndpointAuthBase, APIEndpointAuthorize), nil)
// line 124
req, err := http.NewRequest("GET", APIEndpointTokenVerify, nil)
```
The expected urls are `https://access.line.me/oauth2/v2.1/authorize` and `https://api.line.me/oauth2/v2.1/verify` respectively. However, the above code will give `https:/access.line.me/oauth2/v2.1/authorize` and `https:/api.line.me/oauth2/v2.1/verify`.

**Comment by minghsu0107** [comment]
The issue has been addressed in [this](https://l.facebook.com/l.php?u=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F34668012%2Fcombine-url-paths-with-path-join%3Fanswertab%3Dactive%26fbclid%3DIwAR2iPAlS-xkGoE4K0KV3566U3ZevGuyvSq_EiV8wY8ulQn3Y86f9yWQk-1w%23tab-top&h=AT0HIpXCZPqBDPEQf1exBtdEWx0wc6VfLI_s6SFysECFtAomOUatxf7l6u10fmBnSsIogTGsrLVj1woz653v_bd_FYlYaD5X_glPNNLM91hXLUVXDdlla2hLV7Phk_dIhesnXcEGpW4) discussion.

**Comment by kkdai** [comment]
Hi @minghsu0107 
Thank you, would you please help to provide a PR for this issue?
